### ISSUE TITLE
Create a function that prints numbers from 1 to 5.

### ISSUE THREAD

**Issue by udarakalpana** [nethmiprathibha/javascript_test#1]

**Comment by udarakalpana** [comment]
i need to create function for the generate numbers 1 to 5. It should want to output in the console.

**Comment by udarakalpana** [comment]
@nethmiprathibha please get back this ticket for the in progress bar. because still not have show your changes in the master branch. 

before the start task please break a new branch from the master branch. to do it please get support from the chatgpt.

you commit msg is wrong

**Comment by nethmiprathibha** [comment]
aiyee

**Comment by udarakalpana** [comment]
***For the read this open project from the vs code editor. don't compare it with github pull request code. because code line is difference.**

index.html file line 15 to 21
in that script tag i have declared new const array variable as numbers and have assign a values for it.

after that i have declared a another new variable name is sortedNumbersResult, for this variable i get values from calling the sortedGivenNumber function. for the call sortedGivenNumber function i passed numbers variable as an argument for it. this function has create in executeCommand.js file.

executeCommand.js file line 1 to 3
i have declared sortedGivenNumber function and getting numbers as a parameter for execute function code. inside the function code i returned sored numbers. that return value is will assign to the sortedNumbersResult variable which located in index.html file first script tag.

after it, in the index.html file line 18 sortedNumbersResult variable value will be append to the p tag

**Comment by nethmiprathibha** [comment]
Thank you.
Task 02
I opened vs code.
 index.html line number 24 to 29
in that script tag i have declared new const array variable as numbers and have assign a values for it.
i have declared generate numbers function inside the function I give variable and value numbers OneToFive  this function has create in executeCommand.js file.

executeCommand.js file line 4 to 11.
i have Appreciated generatenumbers function and getting numbers rfor execute function code. in the function code i returned print one to five numbers. that return value is will give to the onetofive NumbersResult variable what situated in index.html file first script tag.
after it, in the index.html file line 28 OneToFive NumbersResult variable value will be append to the p tag
